---
title: "Fast and Sample-Accurate R-Peak Detectors Based on Visibility Graphs"
author: |
  | Jonas Emrich, Taulant Koka, Sebastian Wirth, Michael Muma
  |
  | Technische Universität Darmstadt
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    highlight: pygments
    toc: yes
    toc_depth: 1
    toc_float: yes
    css: vignette_styles.css
    keep_md: yes
  prettydoc::html_pretty:
    theme: tactile
    highlight: vignette
    toc: yes
    toc_depth: 2
link-citations: true
  # md_document:
  #   variant: markdown_github

toc-title: "Table of Contents"    
csl: the-annals-of-statistics.csl # citation style https://www.zotero.org/styles
bibliography: refs.bib
nocite: |
  @emrich_vg_2023, @koka_vg_2022
vignette: |
  %\VignetteKeyword{ECG, R-peak detection, Visibility graph}
  %\VignetteEncoding{UTF-8}
  %\VignetteIndexEntry{Fast and Sample-Accurate R-Peak Detectors Based on Visibility Graphs}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r, include = FALSE}
# Store user's options()
old_options <- options()

library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.align = "center",
  fig.retina = 2,
  out.width = "85%",
  dpi = 96
  # pngquant = "--speed=1"
)
options(width = 80)
```

------------------------------------------------------------------------

# Motivation

This Python package provides an implementation of visibility graph (VG) based approaches for detecting R-peaks in ECG signals. The utilized visibility graph transformation maps a given signal into a graph representation by expressing sampling locations as nodes and establishing edges between mutually visible samples.
Subsequently, graph information is used to determine the R-peak positions.

In @emrich_vg_2023 and @koka_vg_2022 benchmarking on several popular databases showed that the visibility graph based methods allow for sample-accurate R-peak detection and provide significantly superior performance compared to popular R-peak detectors.

# Installation

You can install the latest version of the 'vg-ecg-detectors' package from the [Python Package Index (PyPI)](https://pypi.org/project/vg-ecg-detectors/) by running:

```         
pip install vg-ecg-detectors
```

Additionally, the source code is available on [GitHub](https://github.com/JonasEmrich/vg-ecg-detectors).

# Quick Start

In the following, the basic usage of the 'FastNVG' and 'FastWHVG' detectors [@emrich_vg_2023] is illustrated, which utilize the natural visibility graph (NVG) and weighted horizontal visibility graph (WHVG), respectively.

The package provides for both detectors an identically named class that is initialized with the *sampling frequency* 'fs' of the given ECG signal. R-peaks can then be determined by calling the detectors `find_peaks(ecg)` method and passing the ECG signal.

This is exemplified in the following by means of the pseudo variables `fs` and `ecg`:

-   FastNVG

```{python, eval=FALSE}
from vg_beat_detectors import FastNVG

detector = FastNVG(sampling_frequency=fs)
rpeaks = detector.find_peaks(ecg)
```

-   FastWHVG

```{python, eval=FALSE}
from vg_beat_detectors import FastWHVG

detector = FastWHVG(sampling_frequency=fs)
rpeaks = detector.find_peaks(ecg)
```

## Complete Working Example

The next example demonstrates the application of the 'FastNVG' detector using real-world ECG data provided by the 'scipy' package.
The utilization of the 'FastWHVG' is analogous.

```{python, eval=TRUE}
# import the FastNVG detector
from vg_beat_detectors import FastNVG

# import packages used in this example
import numpy as np
import matplotlib.pyplot as plt
from scipy.misc import electrocardiogram

# generate some ECG signal
fs = 360
ecg = electrocardiogram() # sampling frequency of this excerpt is 360Hz
time = np.arange(ecg.size) / fs

# visibility graph R-peak detector
detector = FastNVG(sampling_frequency=fs)
R_peaks = detector.find_peaks(ecg)

# plot signal and detected peaks
plt.plot(time,ecg)
plt.plot(time[R_peaks],ecg[R_peaks],'X')
plt.xlabel("time in s")
plt.ylabel("ECG in mV")
plt.xlim(9, 10.2)
plt.ylim(-1, 1.5)
plt.show()
```

------------------------------------------------------------------------

# Advanced Usage

For advanced and experimental usage the package provides the 'VisGraphDetector' base class in which a number of parameters can be set which will be briefly explained in the next paragraphs. For further understanding of the listed options and their influence on the algorithm, you might want to consult the papers @emrich_vg_2023 and @koka_vg_2022.

The advanced usage follows the same structure as presented above:

```{python, eval=FALSE}
from vg_beat_detectors import VisGraphDetector

detector = VisGraphDetector(sampling_frequency=250,
                            graph_type='nvg',
                            edge_weight=None,
                            beta=0.55,
                            accelerated=False,
                            window_overlap=0.5,
                            window_length=2,
                            lowcut=4.0)
                            
rpeaks = detector.find_peaks(ecg)
```

## Visibility graph types

The underlying visibility graph transformation can be selected with `graph_type`. The option 'nvg' results in the natural visibility graph and 'hvg' in the horizontal visibility graph.

## Weighted edges

The edges in the visibility graph representation can be constructed with a weighting factor. Therefore, the option `edge_weight` determines the metric for calculating the edge weight between two nodes (or samples).

Available weights are 'distance', 'sq_distance', 'v_distance', 'abs_v\_distance', 'h_distance', 'abs_h\_distance', 'slope', 'abs_slope', 'angle' and 'abs_angle' as well as None for no weighting.

For further explanation of each available weight see the [documentation of the 'ts2vg' package](https://cbergillos.com/ts2vg/api/graph_options.html#weighted-graphs)

## Accelerated and non-accelerated processing

The acceleration technique proposed in [@emrich_vg_2023] which reduces the input signal to only local maxima samples can be enabled or disabled by setting `accelerated` to `True` or `False`, respectively. The acceleration results in a reduced run-time by one order of magnitude while the detection accuracy remains comparable with the non-accelerated detector.

## Sparsity parameter $\beta$

As described in @emrich_vg_2023 and @koka_vg_2022 the choice of the sparsity parameter $\beta \in [0, 1]$ depends on the used visibility graph transformation and edge weights and is a crucial setting for a well-functioning detector. Sparsity parameter values for the NVG and WHVG were determined by numerical experiments in @emrich_vg_2023 and @koka_vg_2022. We highly recommend redetermining `beta` as described in @emrich_vg_2023 and @koka_vg_2022, when changes have been made to the `graph_type` and `edge_weight` options.

## Adjusting segments

The input ECG signal is processed segment-wise using segments with a default length of $2 \sec$ and an overlap of $50\%$, i.e., `window_length=2` and `window_overlap=0.5`. Therefore, these parameters allow for adjustments to the segment-wise computation.

## Setting highpass cutoff frequency

To change the lower cutoff frequency of the highpass filter that pre-processes the input ECG signal, the parameter `lowcut` can be modified The default value is $4 \mathrm{Hz}$.


# References {.unnumbered}

<!-- <div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0px;"></div> -->
